# Configurazione centralizzata per tutte le regex e pattern
# Garantisce coerenza tra anonimizzazione, pattern detection e template generation

# Pattern di anonimizzazione
anonymization:
  patterns:
    ip_address:
      regex: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
      replacement: "<IP>"
      description: "Indirizzi IPv4"
      priority: 1
    
    ipv6_address:
      regex: "\\b(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}\\b"
      replacement: "<IPV6>"
      description: "Indirizzi IPv6"
      priority: 1
    
    mac_address:
      regex: "([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})"
      replacement: "<MAC>"
      description: "Indirizzi MAC"
      priority: 2
    
    fortinet_device_id:
      regex: "FGT[0-9A-Z]{8,}"
      replacement: "<FORTINET_DEVICE>"
      description: "ID dispositivi Fortinet"
      priority: 3
    
    device_name:
      regex: 'devname="([^"]+)"'
      replacement: 'devname="<DEVICE_NAME>"'
      description: "Nomi dispositivi"
      priority: 4
    
    hostname:
      regex: 'hostname="([^"]+)"'
      replacement: 'hostname="<HOSTNAME>"'
      description: "Hostname"
      priority: 4
    
    username:
      regex: 'user=([^\s]+)'
      replacement: 'user=<USERNAME>'
      description: "Nomi utente"
      priority: 5
    
    session_id:
      regex: 'sessionid=(\\d+)'
      replacement: 'sessionid=<SESSION_ID>'
      description: "ID di sessione"
      priority: 6
    
    log_id:
      regex: 'logid="([^"]+)"'
      replacement: 'logid="<LOG_ID>"'
      description: "ID di log"
      priority: 6
    
    timestamp_unix:
      regex: '\\b\\d{10,19}\\b'
      replacement: "<UNIX_TIMESTAMP>"
      description: "Timestamp Unix"
      priority: 7
    
    sequence_number:
      regex: 'idseq=(\\d+)'
      replacement: 'idseq=<SEQ_NUM>'
      description: "Numeri di sequenza"
      priority: 8
    
    port_number:
      regex: '(?:srcport|dstport)=(\\d+)'
      replacement: '\\1=<PORT>'
      description: "Numeri di porta"
      priority: 9
    
    version:
      regex: 'logver=(\\d+)'
      replacement: 'logver=<VERSION>'
      description: "Versioni di log"
      priority: 10

# Pattern per la detection
pattern_detection:
  patterns:
    ip_address:
      regex: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
      description: "Indirizzi IPv4"
      category: "network"
    
    ipv6_address:
      regex: "\\b(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}\\b"
      description: "Indirizzi IPv6"
      category: "network"
    
    mac_address:
      regex: "([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})"
      description: "Indirizzi MAC"
      category: "network"
    
    unix_timestamp:
      regex: "\\b\\d{10,19}\\b"
      description: "Timestamp Unix"
      category: "timestamp"
    
    status_code:
      regex: '\\b(\\d{3})\\b'
      description: "Codici di stato HTTP"
      category: "http"
    
    email:
      regex: '\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b'
      description: "Indirizzi email"
      category: "personal"
    
    url:
      regex: 'https?://[^\s<>"]+|www\.[^\s<>"]+'
      description: "URL"
      category: "network"

# Configurazione template generation
template_generation:
  # Se True, genera template anonimizzati coerenti
  generate_anonymized_templates: true
  
  # Pattern per la generazione di template generici
  generic_patterns:
    numbers: "\\b\\d+\\b"
    strings: '"([^"]*)"'
    dates: "\\d{4}-\\d{2}-\\d{2}"
    times: "\\d{2}:\\d{2}:\\d{2}"
  
  # Placeholder per template generici
  placeholders:
    number: "<NUM>"
    string: "<STR>"
    date: "<DATE>"
    time: "<TIME>"

# Configurazione Drain3
drain3:
  # Parametri per il miner originale
  original:
    depth: 4
    max_children: 100
    max_clusters: 1000
    similarity_threshold: 0.4
  
  # Parametri per il miner anonimizzato
  anonymized:
    depth: 4
    max_children: 100
    max_clusters: 1000
    similarity_threshold: 0.4
  
  # Parametri comuni (fallback)
  depth: 4
  max_children: 100
  max_clusters: 1000
  similarity_threshold: 0.4
