anonymization_patterns:
  credit_card:
    pattern: r'\b\d{4}[- ]?\d{4}[- ]?\d{4}[- ]?\d{4}\b'
    priority: 4
    replacement: '****-****-****-****'
  date:
    pattern: r'\b\d{4}-\d{2}-\d{2}\b'
    priority: 8
    replacement: <DATE>
  device_id:
    pattern: r'\b[A-Z]{2,}[A-Z0-9]{8,}\b'
    priority: 17
    replacement: <DEVICE_ID>
  device_name:
    pattern: r'\b(?:mg-|dev-|prod-|test-)[a-zA-Z0-9_-]+\b'
    priority: 16
    replacement: <DEVICE_NAME>
  email:
    pattern: r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    priority: 3
    replacement: <EMAIL>
  fortinet_device:
    pattern: r'\bFGT[A-Z0-9]{12,}\b'
    priority: 15
    replacement: <FORTINET_DEVICE>
  hostname:
    pattern: r'\b[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.[a-zA-Z]{2,}\b'
    priority: 18
    replacement: <HOSTNAME>
  ip_address:
    pattern: r'\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b'
    priority: 1
    replacement: <IP>
  mac_address:
    pattern: r'\b([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})\b'
    priority: 2
    replacement: <MAC>
  number:
    pattern: r'\b\d{5,}\b'
    priority: 12
    replacement: <NUM>
  path:
    pattern: r'(?:^|\s)(?:[\\\/][^\\\/\s]+(?:[\\\/][^\\\/\s]+)*|[a-zA-Z]:[\\\/][^\\\/\s]+(?:[\\\/][^\\\/\s]+)*)'
    priority: 13
    replacement: <PATH>
  phone:
    pattern: r'\b\d{3}[-.]?\d{3}[-.]?\d{4}\b'
    priority: 6
    replacement: '***-***-****'
  sequence:
    pattern: r'\b\d{10,}\b'
    priority: 11
    replacement: <SEQ_NUM>
  ssn:
    pattern: r'\b\d{3}-\d{2}-\d{4}\b'
    priority: 5
    replacement: '***-**-****'
  time:
    pattern: r'\b\d{2}:\d{2}:\d{2}\b'
    priority: 9
    replacement: <TIME>
  timestamp:
    pattern: r'\b\d{4}-\d{2}-\d{2}[T\s]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})?\b'
    priority: 7
    replacement: <TIMESTAMP>
  url:
    pattern: r'https?://[^\s]+'
    priority: 14
    replacement: <URL>
  version:
    pattern: r'\b(?:v?)?\d+\.\d+(?:\.\d+)?(?:-[a-zA-Z0-9]+)?\b'
    priority: 10
    replacement: <VERSION>
cleaning_patterns:
  csv_header_clean:
    description: Clean CSV headers
    pattern: r'[^a-zA-Z0-9_]'
    replacement: _
  multiple_underscore:
    description: Remove multiple underscores
    pattern: r'_+'
    replacement: _
  timestamp_clean:
    description: Clean timestamp format
    pattern: r'(\d{2}-\d{2}),(\d{2}:\d{2}:\d{2}\.\d+)'
    replacement: \1 \2
config:
  application_order: priority
  cache_size: 100
  default_flags: IGNORECASE
  enable_cache: true
  timeout_ms: 1000
parsing_patterns:
  apache_clf:
    description: Apache Common Log Format
    pattern: r'^(?P<ip>\S+) \S+ \S+ \[(?P<timestamp>[^\]]+)\] "(?P<request>[^"]*)"
      (?P<status>\d+) (?P<bytes>\S+)'
  apache_combined:
    description: Apache Combined Log Format
    pattern: r'^(?P<ip>\S+) \S+ \S+ \[(?P<timestamp>[^\]]+)\] "(?P<request>[^"]*)"
      (?P<status>\d+) (?P<bytes>\S+) "(?P<referer>[^"]*)" "(?P<user_agent>[^"]*)"'
  cef:
    description: Common Event Format
    pattern: r'^CEF:(?P<version>\d+)\|(?P<device_vendor>[^|]*)\|(?P<device_product>[^|]*)\|(?P<device_version>[^|]*)\|(?P<device_event_class_id>[^|]*)\|(?P<name>[^|]*)\|(?P<severity>[^|]*)\|(?P<extension>.*)$'
  cisco:
    description: Cisco log format
    pattern: r'^<(?P<priority>\d+)>(?P<timestamp>\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}\.\d+):\s+%(?P<facility>\w+)-(?P<severity>\d+)-(?P<mnemonic>\w+):\s+(?P<content>.*)$'
  facility_severity:
    description: Syslog with explicit facility.severity
    pattern: r'^<(?P<facility>\w+)\.(?P<severity>\w+)>(?P<timestamp>\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2})\s+(?P<hostname>\S+)\s+(?P<tag>[^:\s]+):\s+(?P<content>.*)$'
  fortinet:
    description: Fortinet log format
    pattern: r'\b(logver|devid|devname|type|level|srcip|dstip|action)\s*='
  key_value:
    description: Key-value pairs in log entries
    pattern: r'(\w+)=([^=]*?)(?=\s+\w+=|$)'
  linux:
    description: Linux log format
    pattern: r'^<(?P<priority>\d+)>(?P<timestamp>\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2})\s+(?P<hostname>\S+)\s+(?P<tag>[^:\s]+)(?:\[(?P<pid>\d+)\])?:?\s*(?P<content>.*)$'
  loghub:
    description: Loghub format
    pattern: r'^(?P<timestamp>\d{8}-\d{2}:\d{2}:\d{2}:\d{3})\|(?P<component>[^|]+)\|(?P<user_id>\d+)\|(?P<message>.*)$'
  no_priority:
    description: Syslog without priority
    pattern: r'^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})?)\s+(?P<hostname>\S+)\s+(?P<tag>[^:\s]+)(?:\[(?P<pid>\d+)\])?:?\s*(?P<content>.*)$'
    enrichment:
      - name: "extract_level_from_content"
        source_field: "content"
        pattern: '^\s*\[(?P<level>[A-Z]+)\]\s*(?P<content>.*)$' # Estrae [LEVEL] e pulisce il messaggio
  rfc3164:
    description: Syslog RFC3164 format
    pattern: r'^<(?P<priority>\d+)>(?P<timestamp>\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}(?:\.\d+)?)\s+(?P<hostname>\S+)\s+(?P<tag>[^:\s]+)(?:\[(?P<pid>\d+)\])?:?\s*(?P<content>.*)$'
  rfc5424:
    description: Syslog RFC5424 format
    pattern: r'^<(?P<priority>\d+)>(?P<version>\d+)\s+(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})?)\s+(?P<hostname>\S+)\s+(?P<app_name>\S+)\s+(?P<proc_id>\S+)\s+(?P<msg_id>\S+)\s+(?P<structured_data>\S*)\s+(?P<message>.*)$'
  windows_event_advanced:
    pattern: "Event Time,Machine Id,Computer Name,Action Type,File Name,Folder Path"
    parser_type: "generic_csv"
    delimiter: ","
    fields: [
      "event_time", "machine_id", "computer_name", "action_type", "file_name", 
      "folder_path", "sha1", "sha256", "md5", "process_command_line", 
      "account_domain", "account_name", "account_sid", "logon_id", "process_id", 
      "process_creation_time", "process_token_elevation", "registry_key", 
      "registry_value_name", "registry_value_data", "remote_url", "remote_computer_name", 
      "remote_ip", "remote_port", "local_ip", "local_port", "file_origin_url", 
      "file_origin_ip", "initiating_process_sha1", "initiating_process_sha256", 
      "initiating_process_file_name", "initiating_process_folder_path", 
      "initiating_process_id", "initiating_process_command_line", 
      "initiating_process_creation_time", "initiating_process_integrity_level", 
      "initiating_process_token_elevation", "initiating_process_parent_id", 
      "initiating_process_parent_file_name", "initiating_process_parent_creation_time", 
      "initiating_process_md5", "initiating_process_account_domain", 
      "initiating_process_account_name", "initiating_process_account_sid", 
      "initiating_process_logon_id", "report_id", "additional_fields", 
      "typed_details", "app_guard_container_id", "protocol", "logon_type", 
      "process_integrity_level", "registry_value_type", "previous_registry_value_name", 
      "previous_registry_value_data", "previous_registry_key", "file_origin_referrer_url", 
      "sensitivity_label", "sensitivity_sub_label", "is_endpoint_dlp_applied", 
      "is_azure_info_protection_applied", "alert_ids", "categories", "severities", 
      "is_marked", "data_type"
    ]
    confidence: 0.95
    nested_fields:
      - field_name: "typed_details"
        parser_type: "generic_kv"
        delimiter: "/"
        kv_separator: ":"
  windows_event_simple:
    pattern: "Event Time,Machine Id,Computer Name,Action Type"
    parser_type: "generic_csv"
    delimiter: ","
    fields: ["event_time", "machine_id", "computer_name", "action_type"]
    confidence: 0.9
  android_log:
    pattern: "LineId,Date,Time,Pid,Tid,Level,Component,Content"
    parser_type: "generic_csv"
    delimiter: ","
    fields: ["line_id", "date", "time", "pid", "tid", "level", "component", "content"]
    confidence: 0.9
  fortinet_log_kv:
    pattern: "logver=.*devid=.*" # Pattern più robusto
    parser_type: "generic_kv"
    delimiter: " " # Spazio come delimitatore principale
    kv_separator: "="
    confidence: 0.85
  apache_access_simple:
    pattern: '^\\S+ \\S+ \\S+ \\[[^\\]]+\\] "[^"]*" \\d+ \\d+'
    parser_type: "apache_regex" # Da implementare
    confidence: 0.8
  # timestamp_pipe_format:  # Temporaneamente disabilitato
  #   pattern: '^(\\d{8}-\\d{2}:\\d{2}:\\d{2}:\\d{3})\\|([^|]+)\\|(\\d+)\\|(.+)$'
  #   fields:
  #     - name: "timestamp"
  #       group: 1
  #     - name: "component"
  #       group: 2
  #     - name: "id"
  #       group: 3
  #     - name: "message"
  #       group: 4
  #   confidence: 0.6
  syslog_format:
    pattern: '^(\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d+Z)\\s+(\\S+)\\s+(\\S+):\\s*(.+)$'
    fields:
      - name: "timestamp"
        group: 1
      - name: "hostname"
        group: 2
      - name: "service"
        group: 3
      - name: "message"
        group: 4
    confidence: 0.95
  syslog_bracket_format:
    pattern: '^(\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d+Z)\\s+(\\S+)\\s+(\\S+)\\[(\\d+)\\]:\\s*(.+)$'
    fields:
      - name: "timestamp"
        group: 1
      - name: "hostname"
        group: 2
      - name: "service"
        group: 3
      - name: "pid"
        group: 4
      - name: "message"
        group: 5
    confidence: 0.95
  # git_config_format:
  #   pattern: '^\\[([^\\]]+)\\]$'
  #   fields:
  #     - name: "section"
  #       group: 1
  #   confidence: 0.9
  # git_config_key_value:
  #   pattern: '^([^\\s=]+)\\s*=\\s*(.+)$'
  #   fields:
  #     - name: "key"
  #       group: 1
  #     - name: "value"
  #       group: 2
  #   confidence: 0.9
  timestamp_bracket_format:
    pattern: '^(\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2})\\s+(\\S+)\\[(\\d+)\\]:\\s*(.+)$'
    fields:
      - name: "timestamp"
        group: 1
      - name: "component"
        group: 2
      - name: "id"
        group: 3
      - name: "message"
        group: 4
  timestamp_level_format:
    pattern: '^(\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2})\\s+(\\w+)\\s+(\\S+):\\s*(.+)$'
    fields:
      - name: "timestamp"
        group: 1
      - name: "level"
        group: 2
      - name: "component"
        group: 3
      - name: "message"
        group: 4
security_patterns:
  auth:
    description: Authentication indicators
    flags: IGNORECASE
    pattern: r'\b(auth|login|password|credential)\b'
  critical:
    description: Critical indicators
    flags: IGNORECASE
    pattern: r'\b(critical|fatal|panic)\b'
  error:
    description: Error indicators
    flags: IGNORECASE
    pattern: r'\b(error|err|exception|fail|failed)\b'
  network:
    description: Network indicators
    flags: IGNORECASE
    pattern: r'\b(connection|network|ip|port|socket)\b'
  warning:
    description: Warning indicators
    flags: IGNORECASE
    pattern: r'\b(warning|warn|alert)\b'

normalization_patterns:
  timestamp_normalization:
    name: "timestamp_normalization"
    rules:
      - name: "date_time_separated"
        pattern: '(\\d{2}-\\d{2}),(\\d{2}:\\d{2}:\\d{2}\\.\\d+)'
        replacement: '{year}-\\1 \\2'
      - name: "iso_timestamp"
        pattern: '(\\d{4}-\\d{2}-\\d{2})T(\\d{2}:\\d{2}:\\d{2})'
        replacement: '\\1 \\2'
